class CoreApiError(Exception): ...
class CoreApiBadRequestError(CoreApiError): ...
class CoreApiUnauthorizedError(CoreApiError): ...
class CoreApiForbiddenError(CoreApiError): ...
class CoreApiNotFoundError(CoreApiError): ...